### ISSUE TITLE
INFOGRAFIA - ARCANGEL GONZALEZ CRUZ

### ISSUE THREAD

**Issue by ArcangelGC** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-ArcangelGC#1]
[INFOGRAFIA LIBRERIAS - ARCANGEL GONZALEZ CRUZ_compressed.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-ArcangelGC/files/14528131/INFOGRAFIA.LIBRERIAS.-.ARCANGEL.GONZALEZ.CRUZ_compressed.pdf)

**Comment by Kim-Mendoza3** [comment]
Calificacion 19

**Comment by josealfredo79** [comment]
bien hecho y revisado..
